name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-count: 1
          output-file: false
          skip-on-empty: true
